name: Girl With Kaleidoscope Eyes
favicon: null
layout_spectrum: 0.76557
typography_spectrum: 1
title: Girl With Kaleidoscope Eyes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#539dc0'
    - '#ee5a2a'
    - '#e2c416'
    - '#8c5263'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
